name: Build Libs

on:
  workflow_dispatch:

env:
  SDL_VERSION: release-3.4.0

jobs:
  Build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win-x64
            lib: SDL3.dll
          - os: macos-latest
            target: osx
            lib: libSDL3.dylib
          - os: ubuntu-latest
            target: linux-x64
            lib: libSDL3.so
    runs-on: ${{matrix.os}}
    steps:
      - name: Clone SDL3
        run: git clone --depth 1 --branch ${{env.SDL_VERSION}} https://github.com/libsdl-org/sdl sdl3-src
      - name: Setup macOS universal build
        if: ${{ runner.os == 'macOS' }}
        run: echo "CMAKE_EXTRA_ARGS=-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" >> $GITHUB_ENV
      - name: Setup Linux dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make \
            pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
            libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
      - name: Build SDL3
        shell: bash
        run: |
          cmake -B build -S sdl3-src \
            -DCMAKE_BUILD_TYPE=Release \
            -DSDL_TEST_LIBRARY=OFF \
            -DSDL_SHARED=ON \
            -DSDL_STATIC=OFF \
            $CMAKE_EXTRA_ARGS
          cmake --build build --config Release
      - name: Collect Artifact
        shell: bash
        run: find build -name "${{matrix.lib}}" -exec cp {} . \;
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target}}
          path: ${{matrix.lib}}
  UpdateLibs:
    if: github.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download libs
        uses: actions/download-artifact@v4
        with:
          path: Framework/Internal/Native
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: Updated native libs
          committer_name: GitHub Actions
          committer_email: actions@github.com
